# see: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"    
    reviewers:
      - "yuokada"
  - package-ecosystem: "pip"
    directory: "/roles/jupyter/files"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"    
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"    
    open-pull-requests-limit: 3
    reviewers:
      - "yuokada"
    ignore:
      - dependency-name: "pygments"
      - dependency-name: "nbconvert"
      - dependency-name: "urllib3"
      - dependency-name: "cryptography"
      - dependency-name: "paramiko"
      - dependency-name: "bleach"
      - dependency-name: "mistune"
      - dependency-name: "rsa"
