language: python
sudo: true
python:
  - "3.6"
install:
  - pip3 install ansible ansible-lint
before_script:
  - ansible --version
script:
  - ansible --version
  - ansible-lint --version
  - ansible-playbook -i inventory/web.yml --syntax-check *.yml
  - ansible-lint tasks/*.yml
