---
name: Dependabot auto-merge
on: pull_request

permissions: write-all

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.0.0
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "${{ github.event.pull_request.html_url }}"
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
