name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root --with dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --ignore F821 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --ignore F821 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with Ansiblelint
      continue-on-error: true
      run: |
        poetry run ansible --version
        poetry run ansible-lint --version
        poetry run ansible-lint roles/*/*/*.yml
        poetry run ansible-playbook -i inventory/web.yml --syntax-check *.yml
